[package]
name = "poseidon-rs"
version = "0.0.1"
authors = ["arnaucube <root@arnaucube.com>"]
edition = "2018"
license = "GPL-3.0"
description = "Poseidon hash implementation"

[dependencies]
num = "0.2.0"
num-bigint = "0.2.2"
num-traits = "0.2.8"
blake2 = "0.8"
rustc-hex = "1.0.0"
